services:
  demo-api:
    image: docker.io/lschifferx/demo-api:latest
    container_name: demo-api
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0
    restart: unless-stopped
